config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'survey_types#index'
  resources :survey_types
  resources :survey_questions
  resources :question_types
  resources :survey_screens
  resources :participant_surveys
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/participant_survey.rb
class ParticipantSurvey < ApplicationRecord
  belongs_to :survey_type
  belongs_to :survey_question
end

app/models/question_type.rb
class QuestionType < ApplicationRecord
	enum control_type: [:short_string, :long_text, :date, :rating, :dropdown]
end

app/models/survey_question.rb
class SurveyQuestion < ApplicationRecord
  belongs_to :survey_type
  # enum date: [:MMDDYYYY, :DDMMYYYY, :YYYYMMDD]
  enum date_separator: [:/, :-]
  enum rating: [:stars, :users, :hearts]
  before_create :set_order
	def set_order
	  last_order = SurveyQuestion.maximum(:order)
	  self.order = last_order.to_i + 1
	end
end

app/models/survey_screen.rb
class SurveyScreen < ApplicationRecord
	enum screen_type: [:welcome, :thank_you]
  belongs_to :survey_type
end

app/models/survey_type.rb
class SurveyType < ApplicationRecord
	has_many :survey_questions
	has_many :survey_screens
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/participant_surveys_controller.rb
class ParticipantSurveysController < ApplicationController

	def index
		@participant = ParticipantSurvey.all
		@survey_questions = SurveyQuestion.find(params[:survey_type_id])
	end
end

app/controllers/question_types_controller.rb
class QuestionTypesController < ApplicationController
	def new
		
	end
end

app/controllers/survey_questions_controller.rb
class SurveyQuestionsController < ApplicationController
	expose :survey_question
	expose :question_type
	expose :survey_screen
	expose :survey_questions do
		SurveyQuestion.all
	end
	expose :survey_types do
    SurveyType.all
  end

  def new
	question_type = QuestionType.find_by(control_type: params[:question_type])
  	@survey_question = SurveyQuestion.new(question_type_id: question_type.id)
  end

  def create
  	survey_question.save
  	survey_screen.save
  end

	private
	def survey_question_params
		params.require(:survey_question).permit(:id, :question_title, :question_hint, :is_required, :order, :survey_type_id, :date, :date_separator,:rating,:rating_number, :choice)
	end
end

app/controllers/survey_screens_controller.rb
class SurveyScreensController < ApplicationController
	expose :survey_screen

	expose :survey_types do
    SurveyType.all
  end

  expose :survey_screens do
    SurveyScreen.all
  end



	def create
		@survey_screen = SurveyScreen.new(survey_screen_params)
		p '--------------------'
		p @survey_screen.errors
		p '=================='
		if @survey_screen.save!
			redirect_to survey_screens_path
		end
	end

	private
	def survey_screen_params
		params.require(:survey_screen).permit(:id, :screen_type, :short_text, :long_text, :button_text, :survey_type_id)
	end
end

app/controllers/survey_types_controller.rb
class SurveyTypesController < ApplicationController
	expose :survey_type
	expose :survey_types do
    SurveyType.all
  end

	def create
		# survey_type = SurveyType.new(survey_type_params)
		if survey_type.save
			redirect_to survey_types_path
		end
	end

	private
	def survey_type_params
		params.require(:survey_type).permit(:id, :title)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/paraticipant_surveys_helper.rb
module ParaticipantSurveysHelper
end

app/helpers/question_types_helper.rb
module QuestionTypesHelper
end

app/helpers/survey_questions_helper.rb
module SurveyQuestionsHelper
end

app/helpers/survey_screens_helper.rb
module SurveyScreensHelper
end

app/helpers/survey_types_helper.rb
module SurveyTypesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Survey</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
    <%= yield :body_area %>
    
  </body>
</html>

app/views/participant_surveys/index.html.erb
<%#= render partial: 'survey_questions/survey_string_raw' %>
<% @survey_questions.each do |survey_question| %>
	<%= survey_question.question_title %>
<% end %>

app/views/question_types/new.js.erb
$('#question_type_popup').html("<%= j render 'question_type_form' %>");
$('#new_question_modal').modal();

app/views/survey_questions/_survey_question_all.html.erb
<div class="modal fade" id="all_survey_question_modal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h4 class="modal-title" id="exampleModalLabel">Survey Questions</h4>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <% survey_questions.each do |survey_question| %>
					<%= survey_question.question_title %>
				<% end %>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>

app/views/survey_questions/_survey_question_date.html.erb
<div class="modal fade" id="new_survey_question_modal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="row">
        <div class="col-md-6">
        	<%= form_for survey_question, remote: true do |f| %>
            <%#= form_tag("/duration_stat", method: "get", remote: true) do %>
            <%= f.hidden_field :survey_type_id , value: params[:survey_type_id]%>
            <div class="modal-header">
              <h4 class="modal-title" id="exampleModalLabel">Date</h4>
              <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
              </button>
            </div>
            <div class="modal-body">
              <div class="form-group">
              	<%= f.label :question_title, 'Question', class: 'control-label' %>
          			<%= f.text_field :question_title, class: 'form-control', id: "date_question" %>
              </div>

              <div class="form-group">
                <%= f.label :question_hint, 'Hint', class: 'control-label' %>
                <%= f.text_field :question_hint, class: 'form-control' %>
              </div>
              <div class="row">
                
                <div class="col-md-6 form-group">
                  <%= f.label :date, 'Date Format', class: 'control-label' %>
                  <%= f.select :date,options_for_select([['MMDDYYYY','MM-DD-YYYY'],['DDMMYYYY','DD-MM-YYYY'],['YYYYMMDD','YYYY-MM-DD']]), class: 'form-control', id:  
                  "survey_question_date" %>
                </div>
                
                <div class="col-md-6 form-group">
                  <%= f.label :date_separator, 'Date Format', class: 'control-label' %>
                  <%= f.select :date_separator, SurveyQuestion.date_separators.keys, class: 'form-control' , id: "question_date_separator" %>
                </div>
              </div>
              <div class="form-group">
                <%= f.label :is_required, "Required",class: 'control-label' %>&nbsp;&nbsp;
                <label class="switch-left">
                  <%= f.check_box :is_required %>
                  <span></span>
                </label>
              </div>
             

              <div class="form-group">
                <%#= f.label question_type.control_type, 'Hint', class: 'control-label' %>
                <%#= f.text_field question_type.control_type, class: 'form-control' %>
              </div>

            </div>
            <div class="modal-footer">
              <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
              <%= f.submit "Submit", class: 'btn btn-primary' %>
            </div>
          <% end %>
        </div>
        <div class="col-md-6">
          <div class="col-md-2"></div>
          <div class="col-md-4">
            <div class="jumbotron" id="question_space">
              <div class="date_question"></div>
              <div id="date_format"></div>
              <div id="date_format_separator"></div>
            </div>
          </div>
        </div>

      </div>
    </div>
  </div>
</div>
<script>
  $("#date_question").keyup(function(){
    // console.log($("#date_question").val());
    $(".date_question").empty().append($('#date_question').val());
    console.log($("#survey_question_date").val());

    var date = $("#survey_question_date").val();
    var saperator = $("#survey_question_date_separator").val();
    var complete_date = date.replace(/-/g, saperator);
    document.getElementById("date_format").innerHTML = complete_date;

  });
</script>

app/views/survey_questions/_survey_question_dropdown.html.erb
<div class="modal fade" id="new_survey_question_modal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="row">
        <div class="col-md-6">
        	<%= form_for survey_question, remote: true do |f| %>
            <%#= form_tag("/duration_stat", method: "get", remote: true) do %>
            <%= f.hidden_field :survey_type_id , value: params[:survey_type_id]%>
          <div class="modal-header">
            <h4 class="modal-title" id="exampleModalLabel">Dropdown</h4>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>
          <div class="modal-body">
            <div class="form-group">
            	<%= f.label :question_title, 'Question', class: 'control-label' %>
        			<%= f.text_field :question_title, class: 'form-control', id: "dropdown_question"%>
            </div>

            <div class="form-group">
              <%= f.label :question_hint, 'Hint', class: 'control-label' %>
              <%= f.text_field :question_hint, class: 'form-control' %>
            </div>

            <div class="form-group">
              <%= f.label :choice, 'Choice', class: 'control-label' %>
              <%= f.text_area :choice, class: 'form-control', id: "choice_question" %>
            </div>

            <div class="form-group">
              <%= f.label :is_required, "Required",class: 'control-label' %>&nbsp;&nbsp;
              <label class="switch-left">
                <%= f.check_box :is_required %>
                <span></span>
              </label>
            </div>

          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
            <%= f.submit "Submit", class: 'btn btn-primary' %>
          </div>
          <% end %>
        </div>
        <div class="col-md-6">
          <div class="col-md-2"></div>
          <div class="col-md-4">
            <div class="jumbotron" id="question_space">
              <div class="dropdown_question"></div>
              <div class="choice_question">
                <ul></ul>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<script>
  $("#dropdown_question").keyup(function(){
    // console.log($("#question").val());
    $(".dropdown_question").empty().append($('#dropdown_question').val());
  });
  $("#choice_question").keyup(function(){
     console.log($("#choice_question").val());
    $(".choice_question").empty().append($('#choice_question').val());
  });
</script>

app/views/survey_questions/_survey_question_rating.html.erb
<div class="modal fade" id="new_survey_question_modal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="row">
        <div class="col-md-12">
          <div class="col-md-6">
          	<%= form_for survey_question, remote: true do |f| %>
              <%#= form_tag("/duration_stat", method: "get", remote: true) do %>
              <%= f.hidden_field :survey_type_id , value: params[:survey_type_id]%>
              <div class="modal-header">
                <h4 class="modal-title" id="exampleModalLabel">Rating</h4>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                  <span aria-hidden="true">&times;</span>
                </button>
              </div>
              <div class="modal-body">
                <div class="form-group">
                	<%= f.label :question_title, 'Question', class: 'control-label' %>
            			<%= f.text_field :question_title, class: 'form-control', id: "rating_question" %>
                </div>

                <div class="form-group">
                  <%= f.label :question_hint, 'Hint', class: 'control-label' %>
                  <%= f.text_field :question_hint, class: 'form-control' %>
                </div>

                <div class="form-group">
                  <%= f.label :rating, 'Shape', class: 'control-label' %>
                  <%= f.select :rating, SurveyQuestion.ratings.keys, class: 'form-control' %>
                </div>

                <div class="form-group">
                  <div class="col-sm-10 col-sm-offset-1">
                    <div class="col-md-12" style="padding-left: 0;">
                      <output id="rangeSecondary" style="display: inline-block;">1</output>
                    </div>
                    <div class="col-md-12" style="padding-left: 0; padding-right: 0; padding-bottom: 14px;">
                      <div class="range range-secondary" style="width: 100%;">
                        <%= f.range_field :rating_number, :in => 1..10, :step => 1, onchange: "rangeSecondary.value=value", id: "change_scale" %>
                      </div>
                    </div>
                  </div>
                </div>
                
                <div class="form-group">
                  <%= f.label :is_required, "Required",class: 'control-label' %>&nbsp;&nbsp;
                  <label class="switch-left">
                    <%= f.check_box :is_required %>
                    <span></span>
                  </label>
                </div>

                <div class="form-group">
                  <%#= f.label question_type.control_type, 'Hint', class: 'control-label' %>
                  <%#= f.text_field question_type.control_type, class: 'form-control' %>
                </div>
              </div>
              <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                <%= f.submit "Submit", class: 'btn btn-primary' %>
              </div>
            <% end %>
          </div>
          <div class="col-md-6">
            <div class="col-md-2"></div>
            <div class="col-md-4">
              <div class="jumbotron" id="rating_space">
                <div class="rating_question"></div>
                <div id="rate"></div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
<script>
  $("#rating_question").keyup(function(){
    $(".rating_question").empty().append($('#rating_question').val());
    $("#change_scale").change(function(){
      var range = $("#rangeSecondary").val();
      $("#rate").empty().append("<div id='raty'></div>");
      $("#raty").rateYo({
        maxValue: 10,
        fullStar: true,
         numStars: range
      });
    });
  });
  
</script>

app/views/survey_questions/_survey_question_string.html.erb
<div class="modal fade" id="new_survey_question_modal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="row">
        <div class="col-md-6">
        	<%= form_for survey_question, remote: true do |f| %>
            <%#= form_tag("/duration_stat", method: "get", remote: true) do %>
            <%= f.hidden_field :survey_type_id , value: params[:survey_type_id]%>
          <div class="modal-header">
            <h4 class="modal-title" id="exampleModalLabel">String</h4>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>
          <div class="modal-body">
            <div class="form-group">
            	<%= f.label :question_title, 'Question', class: 'control-label' %>
        			<%= f.text_field :question_title, class: 'form-control', id: "question" %>
            </div>

            <div class="form-group">
              <%= f.label :question_hint, 'Hint', class: 'control-label' %>
              <%= f.text_field :question_hint, class: 'form-control' %>
            </div>

            <div class="form-group">
              <%= f.label :is_required, "Required",class: 'control-label' %>&nbsp;&nbsp;
              <label class="switch-left">
                <%= f.check_box :is_required %>
                <span></span>
              </label>
            </div>

          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
            <%= f.submit "Submit", class: 'btn btn-primary' %>
          </div>
          <% end %>
        </div>
        <div class="col-md-6">
          <div class="col-md-2"></div>
          <div class="col-md-4">
            <div class="jumbotron" id="question_space">
              <div class="question"></div>
            </div>
          </div>
          
          <%#= render partial: 'survey_questions/survey_string_raw', collection: survey_questions, as: :survey_question %>
        </div>
      </div>
    </div>
  </div>
</div>

<script>
  $("#question").keyup(function(){
    console.log($("#question").val());
    $(".question").empty().append($('#question').val());
  });
</script>

app/views/survey_questions/_survey_question_text.html.erb
<div class="modal fade" id="new_survey_question_modal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="row">
        <div class="col-md-6">
        	<%= form_for survey_question, remote: true do |f| %>
            <%#= form_tag("/duration_stat", method: "get", remote: true) do %>
            <%= f.hidden_field :survey_type_id , value: params[:survey_type_id]%>
            <div class="modal-header">
              <h4 class="modal-title" id="exampleModalLabel">Text</h4>
              <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
              </button>
            </div>
            <div class="modal-body">
              <div class="form-group">
              	<%= f.label :question_title, 'Question', class: 'control-label' %>
          			<%= f.text_field :question_title, class: 'form-control', id: "long_question" %>
              </div>

              <div class="form-group">
                <%= f.label :question_hint, 'Hint', class: 'control-label' %>
                <%= f.text_field :question_hint, class: 'form-control' %>
              </div>

              <div class="form-group">
                <%= f.label :is_required, "Required",class: 'control-label' %>&nbsp;&nbsp;
                <label class="switch-left">
                  <%= f.check_box :is_required %>
                  <span></span>
                </label>
              </div>

              <div class="form-group">
                <%#= f.label question_type.control_type, 'Hint', class: 'control-label' %>
                <%#= f.text_field question_type.control_type, class: 'form-control' %>
              </div>
            </div>
            <div class="modal-footer">
              <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
              <%= f.submit "Submit", class: 'btn btn-primary' %>
            </div>
          <% end %>
        </div>
        <div class="col-md-6">
          <div class="col-md-2"></div>
          <div class="col-md-4">
            <div class="jumbotron" id="question_space">
              <div class="long_question"></div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<script>
  $("#long_question").keyup(function(){
    console.log($("#long_question").val());
    $(".long_question").empty().append($('#long_question').val());
  });
</script>

app/views/survey_questions/_survey_string_raw.html.erb
<!-- <div class="portlets-wrapper">
 <div class="row">
  <div id="portlet-1" data-toggle="portlet" class="col-lg-12">
   	<div id="js-survey-question-raw-<%= survey_question.id %>" class="panel panel-default">
      <div class="panel-wrapper portlet-handler">
        <div class="panel-body" draggable="true">
        	<%= survey_question.order %>
          <%= survey_question.question_title %>
        </div>
      </div>
   	</div>
   </div>
</div> -->
<div>
  <div class="panel panel-default" draggable="true" id="js-survey-question-raw-<%= survey_question.id %>">
    <div class="panel-heading portlet-handler">
      <h3 class="panel-title"><%= survey_question.order %></h3>
    </div>
    <div class="panel-body">
      <%= survey_question.question_title %>
    </div>
  </div>
</div>

<script>
	$(function(){
var sPositions = localStorage.positions || "{}",
    positions = JSON.parse(sPositions);
$.each(positions, function (id, pos) {
    $("#" + id).css(pos)
})
$("#js-survey-question-raw-<%= survey_question.id %>").draggable({
    containment: "#containment-wrapper",
    scroll: false,
    stop: function (event, ui) {
        positions[this.id] = ui.position
        localStorage.positions = JSON.stringify(positions)
    }
});
});
</script>

app/views/survey_questions/create.js.erb
<% if survey_question.persisted? %>
	$('#new_survey_question_modal').modal('hide');
	$('#question_string').append("<%= j render partial: '/survey_questions/survey_string_raw',locals: {survey_question: survey_question} %>");
<% end %>

app/views/survey_questions/index.html.erb
<div class="row">
	<div class="col-sm-12" style="margin-top: -55px">
	<%= link_to "Welcome", new_survey_screen_path(survey_type_id: params[:survey_type_id]), remote: true, class: 'btn btn-default' %>
	</div>
</div>	
<div class="row">

	<div class="pull-right">
		<%= link_to "View Question", participant_surveys_path(survey_type_id: params[:survey_type_id]), class: 'btn btn-primary' %>
	</div>
	<div class="col-sm-3 margin-top-10">
		<div class="leftside_admin_btn">
			<%= link_to QuestionType.control_types.key(0).titlecase, new_survey_question_path(survey_type_id: params[:survey_type_id], question_type: QuestionType.control_types.key(0)), remote: true, class: 'btn btn-default' %><br><br>
			<%= link_to QuestionType.control_types.key(1).titlecase, new_survey_question_path(survey_type_id: params[:survey_type_id], question_type: QuestionType.control_types.key(1)), remote: true, class: 'btn btn-default' %><br><br>
			<%= link_to QuestionType.control_types.key(2).titlecase, new_survey_question_path(survey_type_id: params[:survey_type_id], question_type: QuestionType.control_types.key(2)), remote: true, class: 'btn btn-default' %><br><br>
			<%= link_to QuestionType.control_types.key(3).titlecase, new_survey_question_path(survey_type_id: params[:survey_type_id], question_type: QuestionType.control_types.key(3)), remote: true, class: 'btn btn-default' %><br><br>
			<%= link_to QuestionType.control_types.key(4).titlecase, new_survey_question_path(survey_type_id: params[:survey_type_id], question_type: QuestionType.control_types.key(4)), remote: true, class: 'btn btn-default' %>
		</div>
	</div>
	<div class="col-sm-9 margin-top-10" id="question_string">
		<%= render partial: 'survey_questions/survey_string_raw', collection: survey_questions, as: :survey_question %>
	</div>
</div>

<% content_for :body_area do %>
  <div id="survey_question_popup"></div>
  <div id="survey_welcome_screen_popup"></div>
  <div id="index_popup"></div>
<% end %>

app/views/survey_questions/index.js.erb
<%#= render partial: 'survey_questions/survey_question_all' %>
$('#index_popup').html("<%= j render 'survey_question_all' %>");
$('#all_survey_question_modal').modal();

app/views/survey_questions/new.js.erb
<% if params[:question_type].eql?('short_string') %>
	$('#survey_question_popup').html("<%= j render 'survey_question_string' %>");
	$('#new_survey_question_modal').modal();

<% elsif params[:question_type].eql?('long_text') %>
	$('#survey_question_popup').html("<%= j render 'survey_question_text' %>");
	$('#new_survey_question_modal').modal();

<% elsif params[:question_type].eql?('date') %>
	$('#survey_question_popup').html("<%= j render 'survey_question_date' %>");
	$('#new_survey_question_modal').modal();

<% elsif params[:question_type].eql?('rating') %>
	$('#survey_question_popup').html("<%= j render 'survey_question_rating' %>");
	$('#new_survey_question_modal').modal();

<% elsif params[:question_type].eql?('dropdown') %>
	$('#survey_question_popup').html("<%= j render 'survey_question_dropdown' %>");
	$('#new_survey_question_modal').modal();
<% end %>

app/views/survey_screens/_survey_welcome_screen_form.html.erb
<div class="modal fade" id="new_welcome_screen_modal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="row">
        <div class="col-md-6">
        	<%= form_for survey_screen,remote: true  do |f| %>
            <%= f.hidden_field :survey_type_id , value: params[:survey_type_id]%>
            <div class="modal-header">
              <h4 class="modal-title" id="exampleModalLabel">Welcome Screen</h4>
              <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
              </button>
            </div>
            <div class="modal-body">
              <div class="form-group">
                <%= f.label :screen_type, 'Screen Type', class: 'control-label' %>
                <%= f.select :screen_type,SurveyScreen.screen_types.keys, class: 'form-control' %>
              </div>

              <div class="form-group">
              	<%= f.label :long_text, 'Long Text', class: 'control-label' %>
          			<%= f.text_field :long_text, class: 'form-control', id: "welcome_text" %>
              </div>

              <div class="form-group">
                <%= f.label :short_text, 'Short Text', class: 'control-label' %>
                <%= f.text_field :short_text, class: 'form-control' %>
              </div>

              <div class="form-group">
                <%= f.label :button_text, 'Button Text', class: 'control-label' %>
                <%= f.text_field :button_text, class: 'form-control',id: "button_text" %>
                <!-- <div class="button general full enabled hover-effect" style="display: inline-block;">start</div> -->
                <!-- class: "button general full enabled hover-effect" -->
              </div>

            </div>
            <div class="modal-footer">
              <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
              <%= f.submit "Submit", class: 'btn btn-primary', remote: true %>
            </div>
          <% end %>
        </div>
        <div class="col-md-6">
          <div class="col-md-2"></div>
            <div class="col-md-4">
              <div class="jumbotron" id="rating_space">
                <div class="welcome_text"></div>
                <div class="button_text general full enabled hover-effect active" style="display: inline-block;"></div>
              </div>
            </div>
        </div>
      </div>
    </div>
  </div>
</div>
<script>
  $("#welcome_text").keyup(function(){
    $(".welcome_text").empty().append($("#welcome_text").val());  
  });
  $("#button_text").keyup(function(){
    $(".button_text").empty().append($("#button_text").val());
  });
</script>

app/views/survey_screens/create.js.erb
<% if survey_screen.persisted? %>
	$("#new_welcome_screen_modal").modal('hide');
	$('#question_string').append("<%= j render partial: '/survey_questions/survey_string_raw',locals: {survey_question: survey_question} %>");
<% end %>

app/views/survey_screens/index.html.erb
<div class="aside-inner">
	<br>
	<br><br>
	<div class="alert alert-success" style="width: 367px;">
		<%= link_to 'Welcome Screen', new_survey_screen_path(survey_type_id: params[:survey_type_id]), remote: true %>
	</div>
	<div class="alert alert-danger" style="width: 367px; height: 400px;">


	<!-- 	<ul class="column">
			<li class="alert alert-dark" style="width: 50px; height: 10px;">String</li>
			<li class="alert alert-dark" style="width: 50px; height: 10px;">Date</li>
			<li class="alert alert-dark" style="width: 50px; height: 10px;">Dropdown</li>
			<li class="alert alert-dark" style="width: 50px; height: 10px;">Date</li>
			<li class="alert alert-dark" style="width: 50px; height: 10px;">Rating</li>
		</ul> -->
	</div>
	<div class="alert alert-info" style="width: 367px;">
		Thank You
	</div>
</div>

<% content_for :body_area do %>
  <div id="survey_screen_popup"></div>
<% end %>
</div>

app/views/survey_screens/new.js.erb
$('#survey_welcome_screen_popup').html("<%= j render 'survey_welcome_screen_form' %>");
$('#new_welcome_screen_modal').modal();

app/views/survey_types/_survey_raw.html.erb
<div id="js-survey-raw-<%= survey_type.id %>">
	<div class="add_survay_que_box">
	<br><br>
		<%= survey_type.title %>
		<br><br><br><br>
		<%= link_to "Add Questions", survey_questions_path(survey_type_id: survey_type.id), class: 'btn btn-default' %>
		<%#= link_to 'New Photo Album', new_photo_album_path, remote: true, class: 'btn btn-primary btn-lg' %>
	</div>
</div>

app/views/survey_types/create.js.erb
<% if survey_type.persisted? %>
	$('#new_survey_modal').modal('hide');
<% end %>

app/views/survey_types/index.html.erb
<br><br>
<div class="row">
	<div class="col-sm-2 col-md-2">
		<div class="create_platform_box">
			<br><br>
			<%= link_to 'Add Survey', new_survey_type_path, remote: true, class: 'btn btn-primary' %>
			<div class="create_platform_label">
				<p>Create a new Survey</p>
		  </div>
		 </div>
	</div>
	<div class="col-sm-2 col-md-2">
		<%= render partial: 'survey_types/survey_raw', collection: survey_types, as: :survey_type %>
	</div>
</div>


<% content_for :body_area do %>
  <div id='survey_popup'></div>
<% end %>
</div>

app/views/survey_types/new.js.erb
$('#survey_popup').html("<%= j render 'survey_form' %>");
$('#new_survey_modal').modal();